-- Create Database

USE [master]
GO

/****** Object:  Database [Pits]    Script Date: 17-06-2020 15:13:50 ******/
CREATE DATABASE [Pits]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pits', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Pits.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pits_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Pits_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pits].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pits] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pits] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pits] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pits] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pits] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pits] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pits] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pits] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pits] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pits] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pits] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pits] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pits] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pits] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pits] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pits] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pits] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pits] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pits] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pits] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pits] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pits] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pits] SET RECOVERY FULL 
GO

ALTER DATABASE [Pits] SET  MULTI_USER 
GO

ALTER DATABASE [Pits] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pits] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pits] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pits] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pits] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pits] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Pits] SET  READ_WRITE 
GO

